apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-external-secret
  namespace: litellm
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gitlab-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: litellm-secret
    creationPolicy: Owner
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: CLAUDE_API_KEY
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: GEMINI_API_KEY
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: OPENAI_API_KEY
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: LITELLM_MASTER_KEY
    - secretKey: DATABASE_HOST
      remoteRef:
        key: SUPABASE_POSTGRES_HOST
    - secretKey: DATABASE_USERNAME
      remoteRef:
        key: SUPABASE_POSTGRES_USER
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: SUPABASE_POSTGRES_PASSWORD
